actor_lr = 0.001
alpha = 0.2
alpha_lr = 0.0003
auto_alpha = false
batch_size = 256
buffer_size = 1000000
critic_lr = 0.001
domain = "walker"
epoch = 600
frame_skip = 2
gamma = 0.99
hidden_sizes = [256, 256]
n_step = 1
samples = 1000000
seed = 0
start_timesteps = 10000
step_per_collect = 1
step_per_epoch = 5000
task = "walk"
tau = 0.005
update_per_step = 1
